use {graph, widget};


/// An index either given in the form of a publicly instantiated `Widget`'s `WidgetId`, or an
/// internally instantiated `Widget`'s `NodeIndex`,
#[derive(Copy, Clone, Debug, Hash, PartialEq, Eq)]
pub enum Index {
    /// A public identifier given by a user of a conrod library/widget, usually generated by the
    /// `widget_ids` macro.
    Public(usize),
    /// An index to an internal widget, usually used to construct some other widget.
    Internal(graph::NodeIndex),
}


// impl From<widget::Id> for Index {
//     fn from(id: widget::Id) -> Index {
//         Index::Public(id)
//     }
// }

impl From<graph::NodeIndex> for Index {
    fn from(idx: graph::NodeIndex) -> Index {
        Index::Internal(idx)
    }
}
